services:
  - type: web
    name: face-ai-verification-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python-3.10.13
    autoDeploy: true
